version: "3"

services:

    nginx:
        image: nginx:1.20.0
        container_name: deckReview-nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../laravel/:/var/www/
        working_dir: /var/www
        depends_on:
            - php
  
    php:
        build: ./php/
        user: ${user}
        container_name: deckReview-php
        volumes:
            - ../laravel:/var/www
        links:
            - db
        depends_on:
            - db
    
    db:
        build: ./mysql/
        container_name: deckReview-db
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        tty: true

    node:
        image: node:lts-alpine
        volumes:
            - ../laravel:/mnt/laravel
        working_dir: /mnt/laravel
        tty: true
        command: [sh, -c, npm install && npm run dev]